name: 'ships_pj'
version: '1.0.0'

profile: 'dbt_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  ships_pj:
    # ----------------------------------------
    # staging層のモデル設定
    # ----------------------------------------
    staging:
      +materialized: view
      ship_management:
        +schema: stg_ship_management
      route_operations:
        +schema: stg_route_operations
      sales:
        +schema: stg_sales

